#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd wing

blockMesh

snappyHexMesh -overwrite

topoSet

cd ../backgroundMesh

blockMesh

mergeMeshes . ../wing -overwrite

rm -rf 0

cp -r 0.orig 0

topoSet

setFields

echo checkMesh -allTopology -allGeometry >> meshCheck.log
