#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# copy motorbike surface from resources directory


blockMesh

decomposePar

mpirun -np 2 snappyHexMesh -overwrite

reconstructParMesh

rm -rf proc*

#------------------------------------------------------------------------------
